// <auto-generated />
using System;
using BookProject_ASP_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookProject_ASP_MVC.Migrations
{
    [DbContext(typeof(BookDatabase))]
    [Migration("20201124212944_Book")]
    partial class Book
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookProject_ASP_MVC.Models.Book", b =>
                {
                    b.Property<int>("Book_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Book_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_of_publish")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Book_ID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BookProject_ASP_MVC.Models.Customer", b =>
                {
                    b.Property<int>("Cust_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cust_ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("BookProject_ASP_MVC.Models.Rental", b =>
                {
                    b.Property<int>("Rental_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Book_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Book_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Cust_ID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerCust_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Rental_ID");

                    b.HasIndex("Book_ID1");

                    b.HasIndex("CustomerCust_ID");

                    b.ToTable("Rental");
                });

            modelBuilder.Entity("BookProject_ASP_MVC.Models.Rental", b =>
                {
                    b.HasOne("BookProject_ASP_MVC.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("Book_ID1");

                    b.HasOne("BookProject_ASP_MVC.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerCust_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
